fix: stay with paho-mqtt 1.x due to breaking change in 2.0
This fixes psacc crashing with:
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'

paho-mqtt 2.0, released on Feb, 10th, requires additional
arguments to mqtt.Client(), see
https://github.com/eclipse/paho.mqtt.python/blob/v2.0.0/docs/migrations.rst.
So stay with 1.x for now.